name: Build, Test and Deploy React Application

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: Update build version
        id: update_version
        run: echo "BUILD_VERSION=v${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}" >> $GITHUB_ENV
        shell: bash

      # - name: Update README with build version
      #   run: |
      #     if [[ -n $(git status -s) ]]; then
      #       echo "Working directory is not clean, please commit or discard changes."
      #       exit 1
      #     fi
      #   shell: bash

      - name: npm ci, build and test
        run: |
          npm ci
          npm run build --if-present
          npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate jsdoc
        run: npm run jsdoc

      - name: Save artifact
        id: save-artifact
        uses: actions/upload-artifact@v2
        with:
          name: previous-artifact-v${{ env.BUILD_VERSION }}
          path: build

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Aiiishaaa/CI-TP1

  # Deploy job
  deploy:
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ needs.build_test.outputs.pages_url }} # Utilisez la sortie correcte pour obtenir l'URL des pages
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Add a dependency to the build job
    needs: build_test
    # Specify runner + deployment step
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Aiiishaaa/CI-TP1

      - name: Update README with previous version and artifact link
        run: |
          PREVIOUS_VERSION=$(grep -oP 'Version actuelle : \K[0-9]+\.[0-9]+\.[0-9]+' README.md)
          echo "Previous Version: $PREVIOUS_VERSION → [Link to the previous artifact](https://github.com/${{ github.repository }}/actions/runs/${{ needs.build_test.outputs.save-artifact }}/artifacts)" >> README.md
        shell: bash
